### ISSUE TITLE
Wemod stays active after game is quit

### ISSUE THREAD

**Issue by dannyglover** [DaniAsh551/wemod-launcher#42] opened 2024-05-12 16:11 UTC
Hi. Firstly, thanks for this tool, it's great being able to use WeMod on singleplayer games on Linux.

Everything is working fine, except when games are exited (either via the games menu, or Alt+F4), wemod remains open. Closing wemod manually afterwards doesn't stop steam from thinking the game is still running. 

It seems like the wemod process (and the associated wineserver) never ends/completes, so it stays active until the active wine prefix is killed.

Thank you.

**Comment by dannyglover** [comment] 2024-05-12 16:23
Adding the following to the launch commands (at the end) does the trick:

`WINEPREFIX="PATH_TO_GAME_PREFIX" wineserver -k`

**Comment by marvin1099** [comment] 2024-05-13 06:14
True that is how that is working right now.
On Windows WeMod is intended to stay open.
Im not shure if this can be implementet,
we would need to somehow track the game that is started by the wemod-launcher. 
It may be possible, i will look into it.

**Comment by dannyglover** [comment] 2024-05-13 07:51
> True that is how that is working right now.
> On Windows WeMod is intended to stay open.
> Im not shure if this can be implementet,
> we would need to somehow track the game that is started by the wemod-launcher. 
> It may be possible, i will look into it.

Hi.

The main issue isn't even WeMod remaining open, it's that it prevents the game from exiting. So regardless, WeMod has to be terminated if you want to launch another steam game. 

Steam still believes the game is running after exiting, as the WeMod process doesn't return control execution back to the game, it waits for the WeMod program to be exited, which even if exited, doesn't shutdown the wine server it started, thus it creating a situation where the server will remain running in the background until manually shutdown.

If I need to articulate this better, please let me know. 

Thank you.

**Comment by marvin1099** [comment] 2024-05-13 08:12
You might have somewhat missunderstood, wemod needs to run in the same wine prefix as the game, so it will keep open the wine server. To fix this we will need to track only if the game runs in the wine server and if not we need to terminate wemod since wemod will never close by itself.
So that would have to be implementet as code.
The reason why this might be hard is that we need to only track the game and not wemod, since wemod runs in the same prefix, i may need to see what is running exatly and only stop the sever if olny wemod is running.

Well now that i typed it I did get some ideas on how to implement this, mabye its simple to do, i get back to you soon.

**Comment by marvin1099** [comment] 2024-05-16 21:12
Sadly i cant figure out how to implement this, right now I'm really the only active developer,  
therefore i will mark this as help wanted and close this issue for now.

**Closed by marvin1099** 2024-05-16 21:12 UTC
Labels: help wanted

**Comment by DaniAsh551** [comment] 2024-05-19 11:12
> Sadly i cant figure out how to implement this, right now I'm really the only active developer, therefore i will mark this as help wanted and close this issue for now.

We can always wait for the game tasks to finish in `wemod.bat` and then kill the wemod process.

I think implementing this at the bat file level would be simpler than at the python level.

Having said that, I am not sure how beneficial this would prove to be, but then again - I very rarely use WeMod now, so I might not understand how important this is.

**Comment by marvin1099** [comment] 2024-05-19 11:55
> > Sadly i cant figure out how to implement this, right now I'm really the only active developer, therefore i will mark this as help wanted and close this issue for now.
> 
> We can always wait for the game tasks to finish in `wemod.bat` and then kill the wemod process.
> 
> I think implementing this at the bat file level would be simpler than at the python level.
> 
> Having said that, I am not sure how beneficial this would prove to be, but then again - I very rarely use WeMod now, so I might not understand how important this is.

I very rarely use WeMod also, i think there is a way to do it in the bat but it will be hacky.  
What do i mean by that well the problem is we cant get a pid of a started prosess in batch,  
therefore i will have to do something like "getpidof exe" of course this not the real command,  
then what if the game starts a subprosess or what if the game name has wemod as the name itself.
The second one might be unrealistic but my point is the ways to do it are not that great, and cliking one button to close the game if fine therefore after new consideration i don't think it is that important so i will remove the labels.

**Comment by dannyglover** [comment] 2024-05-19 15:27
> > Sadly i cant figure out how to implement this, right now I'm really the only active developer, therefore i will mark this as help wanted and close this issue for now.
> 
> We can always wait for the game tasks to finish in `wemod.bat` and then kill the wemod process.
> 
> I think implementing this at the bat file level would be simpler than at the python level.
> 
> Having said that, I am not sure how beneficial this would prove to be, but then again - I very rarely use WeMod now, so I might not understand how important this is.

Hi. The reasons it's beneficial: 

- WeMod prevents steam from closing the game properly, as its process doesn't end. Clicking the x button in the WeMod app isn't enough to resolve it. For those of us who don't use steam to launch games (and who don't sit at the PC to play), clicking the "close game" button on steam is extremely hard (I had to write a script to work around this, that executes on a controller button combination. 
- The argument was brought up that WeMod isn't meant to close, but that only applies to Windows. The Linux system works with a per game instance of WeMod, so having it stay open after you finish playing a game is completely useless. 

If I haven't elaborated correctly, or you need any further information, please let me know. 

PS: thanks for all your work on this project! My tone above isn't meant to come off as abrasive, just factual.

Cheers :)

**Comment by marvin1099** [comment] 2024-05-19 15:35
> > > Sadly i cant figure out how to implement this, right now I'm really the only active developer, therefore i will mark this as help wanted and close this issue for now.
> > 
> > 
> > We can always wait for the game tasks to finish in `wemod.bat` and then kill the wemod process.
> > I think implementing this at the bat file level would be simpler than at the python level.
> > Having said that, I am not sure how beneficial this would prove to be, but then again - I very rarely use WeMod now, so I might not understand how important this is.
> 
> Hi. The reasons it's beneficial:
> 
>     * WeMod prevents steam from closing the game properly, as its process doesn't end. Clicking the x button in the WeMod app isn't enough to resolve it. For those of us who don't use steam to launch games (and who don't sit at the PC to play), clicking the "close game" button on steam is extremely hard (I had to write a script to work around this, that executes on a controller button combination, which basically finds the active wine process and then uses wineserver to end it).
> 
>     * The argument was brought up that WeMod isn't meant to close, but that only applies to Windows. The Linux system works with a per game instance of WeMod, so having it stay open after you finish playing a game is completely useless.
> 
> 
> If I haven't elaborated correctly, or you need any further information, please let me know.
> 
> PS: thanks for all your work on this project! My tone above isn't meant to come off as abrasive, just factual.
> 
> Cheers :)

As i have sayed it would be a hacky solution, i think about it as a user choice.

**Comment by dannyglover** [comment] 2024-05-19 15:40
> > > > Sadly i cant figure out how to implement this, right now I'm really the only active developer, therefore i will mark this as help wanted and close this issue for now.
> > > 
> > > 
> > > We can always wait for the game tasks to finish in `wemod.bat` and then kill the wemod process.
> > > I think implementing this at the bat file level would be simpler than at the python level.
> > > Having said that, I am not sure how beneficial this would prove to be, but then again - I very rarely use WeMod now, so I might not understand how important this is.
> > 
> > Hi. The reasons it's beneficial:
> > 
> >     * WeMod prevents steam from closing the game properly, as its process doesn't end. Clicking the x button in the WeMod app isn't enough to resolve it. For those of us who don't use steam to launch games (and who don't sit at the PC to play), clicking the "close game" button on steam is extremely hard (I had to write a script to work around this, that executes on a controller button combination, which basically finds the active wine process and then uses wineserver to end it).
> > 
> >     * The argument was brought up that WeMod isn't meant to close, but that only applies to Windows. The Linux system works with a per game instance of WeMod, so having it stay open after you finish playing a game is completely useless.
> > 
> > 
> > If I haven't elaborated correctly, or you need any further information, please let me know.
> > 
> > PS: thanks for all your work on this project! My tone above isn't meant to come off as abrasive, just factual.
> > 
> > Cheers :)
> 
> As i have sayed it would be a hacky solution, i think about it as a user choice.

Seemingly our opinions on this being an issue differs, but to me, when an external program changes the behavior of another, that is a problem. 

I'm not going to argue with you though. If every contributor isn't willing to resolve this, I'll look into it myself and submit a PR if I resolve it in a satisfactory faction. I personally don't believe that making the script checking if the process is launched has ended is "hacky", but logical.

Thank you.

**Comment by marvin1099** [comment] 2024-05-19 16:09
> > > > > Sadly i cant figure out how to implement this, right now I'm really the only active developer, therefore i will mark this as help wanted and close this issue for now.
> > > > 
> > > > 
> > > > We can always wait for the game tasks to finish in `wemod.bat` and then kill the wemod process.
> > > > I think implementing this at the bat file level would be simpler than at the python level.
> > > > Having said that, I am not sure how beneficial this would prove to be, but then again - I very rarely use WeMod now, so I might not understand how important this is.
> > > 
> > > 
> > > Hi. The reasons it's beneficial:
> > > ```
> > > * WeMod prevents steam from closing the game properly, as its process doesn't end. Clicking the x button in the WeMod app isn't enough to resolve it. For those of us who don't use steam to launch games (and who don't sit at the PC to play), clicking the "close game" button on steam is extremely hard (I had to write a script to work around this, that executes on a controller button combination, which basically finds the active wine process and then uses wineserver to end it).
> > > 
> > > * The argument was brought up that WeMod isn't meant to close, but that only applies to Windows. The Linux system works with a per game instance of WeMod, so having it stay open after you finish playing a game is completely useless.
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > If I haven't elaborated correctly, or you need any further information, please let me know.
> > > PS: thanks for all your work on this project! My tone above isn't meant to come off as abrasive, just factual.
> > > Cheers :)
> > 
> > 
> > As i have sayed it would be a hacky solution, i think about it as a user choice.
> 
> Seemingly our opinions on this being an issue differs, but to me, when an external program changes the behavior of another, that is a problem.
> 
> I'm not going to argue with you though. If every contributor isn't willing to resolve this, I'll look into it myself and submit a PR if I resolve it in a satisfactory fashion. I personally don't believe that making the script that launched a process also adding a check to see if that process has ended is "hacky", but logical.
> 
> The reason why I haven't tried myself yet is that you guys wrote the scripts, so it'd be faster for you guys to do this, as you're more familiar with it than I am. That being said, I'm not afraid to get stuck in and contribute.
> 
> Thank you.

The reason why this is a hacky solution is that we have to get the pid after starting the exe and we can not get the pid while starting the exe, at least if we do it in the bat. If you can think of a good way go ahead

**Comment by DaniAsh551** [comment] 2024-05-19 17:10
> Seemingly our opinions on this being an issue differs

Whenever any one of the users has an issue with the tool, I believe it is an issue, but the problem we have right now is that, marvin is the only dev who is actively working on this, while I do some stuff every now and then, I cannot dedicate enough time to do this tool any justice. Where our opinions do differ is (I believe), the priority or urgency of this issue, from my view - I can see some other stuff which has higher priority which might serve more people with the time and effort the devs donate.

> but to me, when an external program changes the behavior of another, that is a problem.

Not sure I follow your logic here

> WeMod prevents steam from closing the game properly, as its process doesn't end. Clicking the x button in the WeMod app isn't enough to resolve it. For those of us who don't use steam to launch games (and who don't sit at the PC to play), clicking the "close game" button on steam is extremely hard (I had to write a script to work around this, that executes on a controller button combination, which basically finds the active wine process and then uses wineserver to end it).

If CMD provides a way to get the PID of the child processes, we could wait for the game and then kill WeMod's pid once the game exits.
Or a simpler way to achieve this would be to start wemod, then start the game with `start /W` (this should wait for the game to exit) and then simply do `taskkill /IM WeMod.exe`. I hope this gives you some idea on how to tackle this if you do decide you would want to go this route.

> If every contributor isn't willing to resolve this, I'll look into it myself and submit a PR if I resolve it in a satisfactory fashion. 

I believe, like I said above, its more to do with getting the most asked-for/critical pieces in place and prioritizing tasks rather than a rejection. The label of `every contributor` equals to just one at the moment and three in the project's entire life so far.

> The reason why I haven't tried myself yet is that you guys wrote the scripts, so it'd be faster for you guys to do this, as you're more familiar with it than I am. That being said, I'm not afraid to get stuck in and contribute.

Having said what I have in the last point, I think this would still be the best approach, since (at the risk of repeating myself too much) we really could use a helping hand or two. That includes solving the issues that are more pronounced to yourself than anyone else.

**Comment by marvin1099** [comment] 2024-05-21 18:07
I decided to add it, since you where interested enough.
I solved it by using the scan for PID by EXE method.
I think this is somewhat hacky, 
but i have added a detection if the game closes fast.
That way i can hopefully prevent games that start sub-processeses to close wemod.

**Comment by dannyglover** [comment] 2024-05-22 00:01
> I decided to add it, since you where interested enough.
> I solved it by using the scan for PID by EXE method in the BAT file.
> I think this is somewhat hacky, 
> but i have added a detection if the game closes fast.
> That way i can hopefully prevent games that start sub-processeses to close wemod.

That's very good of you. I really appreciate it. 

I'll give it a try ASAP. Thank you very much!

@DaniAsh551 regarding your earlier reply, that's totally fair, and I understand your situation.

I've been very ill since I last commented here, so apologies for the delayed response.
