### ISSUE TITLE
After build I can't use WeMod at all

### ISSUE THREAD

**Issue by HrBingR** [DaniAsh551/wemod-launcher#25] opened 2024-03-25 01:01 UTC
After following all the steps, I ran into an issue where the game I wanted to play wouldn't launch due to a missing file in the Steam prefix:

```
Proton: Upgrading prefix from None to GE-Proton7-35 (/home/anthony/.local/share/Steam/steamapps/compatdata/2670630/)
Traceback (most recent call last):
  File "/home/anthony/.local/share/Steam/compatibilitytools.d/GE-Proton7-35/proton", line 1708, in <module>
    g_session.init_session(sys.argv[1] != "runinprefix")
  File "/home/anthony/.local/share/Steam/compatibilitytools.d/GE-Proton7-35/proton", line 1494, in init_session
    g_compatdata.setup_prefix()
  File "/home/anthony/.local/share/Steam/compatibilitytools.d/GE-Proton7-35/proton", line 1026, in setup_prefix
    self.update_builtin_libs(builtin_dll_copy)
  File "/home/anthony/.local/share/Steam/compatibilitytools.d/GE-Proton7-35/proton", line 677, in update_builtin_libs
    with open(self.tracked_files_file, "r") as tracked_files:
FileNotFoundError: [Errno 2] No such file or directory: '/home/anthony/.local/share/Steam/steamapps/compatdata/2670630/tracked_files'
```

So I fixed that by touching the file in question, and now the game and WeMod both launch.

Problem is now in WeMod I get "An error occurred while loading WeMod. You may need to reinstall the app or allow it through your anti-virus software."

My internet is working fine, and hitting retry doesn't help either. Had the same issue when trying to install WeMod manually into a prefix through Lutris previously. In that instance I couldn't use the offline installer as I couldn't find a way to run the installer through Wine as a non-admin user.

Clicking the "Reinstall" button does nothing either.

Funny enough, got this exception (from Steam stderr, running Steam from the terminal) every time I clicked the retry button in WeMod:

```
Unhandled Exception:
System.TypeInitializationException: The type initializer for 'V' threw an exception. ---> System.MissingMethodException: Method not found: bool System.Collections.HashHelpers.IsWellKnownEqualityComparer(object)
  at System.Collections.Generic.HashSet`1[T].Add (T item) [0x00000] in <7a1cc2d67b164134ab358e04ee577310>:0
  at V..cctor () [0x00005] in <bd1f644e767f455ca9456607b0147d12>:0
   --- End of inner exception stack trace ---
  at Z.0 (k 0) [0x00011] in <bd1f644e767f455ca9456607b0147d12>:0
  at 3.0 (System.String[] 0) [0x000be] in <bd1f644e767f455ca9456607b0147d12>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: The type initializer for 'V' threw an exception. ---> System.MissingMethodException: Method not found: bool System.Collections.HashHelpers.IsWellKnownEqualityComparer(object)
  at System.Collections.Generic.HashSet`1[T].Add (T item) [0x00000] in <7a1cc2d67b164134ab358e04ee577310>:0
  at V..cctor () [0x00005] in <bd1f644e767f455ca9456607b0147d12>:0
   --- End of inner exception stack trace ---
  at Z.0 (k 0) [0x00011] in <bd1f644e767f455ca9456607b0147d12>:0
```

From what I could find this could indicate a corrupt .Net installation, but the build went fine from what I could tell; went through the dotnet installation and all.

Unfortunately I've reached the end of what I'm able to troubleshoot from my end.

**Comment by DaniAsh551** [comment] 2024-04-03 07:56
Possibly a duplicate of #24 

Please re-open if you think this is different

**Closed by DaniAsh551** 2024-04-03 07:56 UTC
