### ISSUE TITLE
Game Won't start

### ISSUE THREAD

**Issue by Deadlyspy** [DaniAsh551/wemod-launcher#76] opened 2024-06-04 11:35 UTC
Adding process 13020 for gameID 1868140
Traceback (most recent call last):
  File "/home/deck/wemod-launcher/wemod", line 7, in <module>
    from setup import main
  File "/home/deck/wemod-launcher/setup.py", line 167
    f"Setup completed successfully.\nMake shure the LAUNCH OPTIONS of the game say '{os.path.join(SCRIPT_PATH, "wemod")} %command%'",
                                                                                                                ^^^^^
SyntaxError: f-string: unmatched '('
Uploaded AppInterfaceStats to Steam
Removing process 13020 for gameID 1868140

When any game is started it, it starts and stops. See above for steam in Konsole. Used " /home/deck/wemod-launcher/wemod %command%" in launch options.

**Comment by marvin1099** [comment] 2024-06-04 16:25
I think its fixed now, redownload and try once more.

**Comment by Deadlyspy** [comment] 2024-06-05 03:57
Had the permission error. Fixed that. Crashed on download. Building right now.

**Comment by marvin1099** [comment] 2024-06-05 05:44
It crashed on download?
Could you send the wemod.log file then.
That way i can check problems of the download function.

**Comment by Deadlyspy** [comment] 2024-06-05 07:31
It crashed on build. Download then worked. It's working now.

**Comment by marvin1099** [comment] 2024-06-05 08:07
> It crashed on build. Download then worked. It's working now.

Can you send over the crash reason on build then, so if you could just send the log file / copy the error.

**Comment by Deadlyspy** [comment] 2024-06-05 08:17
[wemod.log](https://github.com/user-attachments/files/15580163/wemod.log)

**Comment by marvin1099** [comment] 2024-06-05 11:31
Well i wasn't able to fix the build bug but, i have added a check for the missing version file error you had at the beginning.
Since the issue is resolved I'm now going to close the issue.

**Closed by marvin1099** 2024-06-05 11:31 UTC
