### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by BeCrimes** [DaniAsh551/wemod-launcher#7] opened 2023-09-14 09:30 UTC
I have been successful following this guide up until the part where I log in to WeMod. The issue I am having isn't even technical. When WeMod is the active window, I cannot open the virtual keyboard. I can open the keyboard first, but it covers over the password box and I can't move the cursor to type there. I can dig out a keyboard and go that route, but just out of curiosity I tried clicking login without full credentials and nothing happened. It didn't seem like it tried to log me in at all and no error message, so I'm not sure the keyboard is going to fix the issue. Am I just fundamentally misunderstanding how to run the steam deck in desktop mode?

**Comment by DaniAsh551** [comment] 2023-09-14 21:50
This is a known issue - but I doubt that we could really "fix" this issue

The problem seems to stem from how the deck activates the on screen keyboard - I think it's simply not able to detect the text input boxes in wemod

For now, using a USB/BT or other external keyboard is the way to go on the deck.

I cannot personally test any solutions as I do not own or have access to a steam deck.

I am keeping this issue open in case someone has more information.

**Comment by BeCrimes** [comment] 2023-09-14 22:46
Figured this was the likely answer and have a keyboard ready to go tonight. Should I be anticipating any other hiccups if I made it this far in the process? After I get it launched with logged in wemod thr first time, am I able to stop using desktop mode?

**Comment by BeCrimes** [comment] 2023-09-17 05:46
Okay...new issue. I am trying to tell WeMod where the file is. I have found the file on the steam deck. But in the virtual windows environment that WeMod sends me into, I can't fine any of my game's exe files

**Comment by DaniAsh551** [comment] 2023-09-17 13:21
> Okay...new issue. I am trying to tell WeMod where the file is. I have found the file on the steam deck. But in the virtual windows environment that WeMod sends me into, I can't fine any of my game's exe files

Check Step 4 under "Setting Up The Game" in the readme

And at this point I invite you to join the channel in WeMod discord: https://discord.gg/Zgyk878e

**Comment by DaniAsh551** [comment] 2023-10-29 03:49
No one has come forth with any helpful information on this issue, so I am going to just close this.

If anyone has any new information which may be helpful, please feel free to reopen.

**Closed by DaniAsh551** 2023-10-29 03:49 UTC
Labels: help wanted

**Comment by marvin1099** [comment] 2024-05-11 13:25
> Okay...new issue. I am trying to tell WeMod where the file is. I have found the file on the steam deck. But in the virtual windows environment that WeMod sends me into, I can't fine any of my game's exe files

Since the main issue seams to be solved
and regarding the new issue:  
All your files will be listed in "Z:\" this is your linux root,   
so it may be under /mnt or /home/$USER where $USER ist your username.  
But apart from this the issue is so old it is probably solved or not wanted at this point so im going to also unpin the issue.
