### ISSUE TITLE
Nothing happens when I try to start the game

### ISSUE THREAD

**Issue by wfmota** [DaniAsh551/wemod-launcher#44] opened 2024-05-17 18:40 UTC
Followed every step of the guide and when I get to step 4.7 to launch the game for the first time, nothing happens! It says launching for a while, blinks a couple times and goes back to the green “PLAY” button. 

I’ve tried deleting the game prefix a few times and tried different versions of GE-PROTON, but always get the same result.

I’m using the Steam Deck, with SteamOS 3.5.19, on Coral Island version 1.0-947

**Comment by marvin1099** [comment] 2024-05-17 21:38
I might have messed up some code, please add your wemod.log file that is located at /home/$user/wemod.log
The $user word will have to be replaced with your username.

**Comment by marvin1099** [comment] 2024-05-18 08:58
Since you say what you never got past step 4.7 make sure that the wemod laucher is downloaded to /home/deck/wemod-laucher/ in there there should be a file called wemod,  
If all of this exists send the contents of the log as mentioned.  
if anything is missing use step 3 once more.
please report back so, if you fixed it or not.
this will be closed in around 3 days otherwise.

**Comment by marvin1099** [comment] 2024-05-18 09:11
I think i found the problem, i fixed it here [commit fix string](https://github.com/DaniAsh551/wemod-launcher/commit/1801e03175535252180266eb6f4867b87a66658d),  
So to fix the problem delete the wemod-laucher folder and run [step 3](https://github.com/DaniAsh551/wemod-launcher?tab=readme-ov-file#step-3-installing-wemod-launcher) once more

**Comment by robangus** [comment] 2024-05-19 10:16
> I think i found the problem, i fixed it here [commit fix string](https://github.com/DaniAsh551/wemod-launcher/commit/1801e03175535252180266eb6f4867b87a66658d), So to fix the problem delete the wemod-laucher folder and run [step 3](https://github.com/DaniAsh551/wemod-launcher?tab=readme-ov-file#step-3-installing-wemod-launcher) once more

I have this issue today (new install right now) and no log file in the wemod launcher folder only the following:
bin file
.git
wemod.bat
wemod ( no ext but shows as python - does this need to be .log)
util.py
setup.py
requirements.txt
readme.md
LICENSE
changelog.md
.gitignore

**Comment by marvin1099** [comment] 2024-05-19 10:36
> > I think i found the problem, i fixed it here [commit fix string](https://github.com/DaniAsh551/wemod-launcher/commit/1801e03175535252180266eb6f4867b87a66658d), So to fix the problem delete the wemod-laucher folder and run [step 3](https://github.com/DaniAsh551/wemod-launcher?tab=readme-ov-file#step-3-installing-wemod-launcher) once more
> 
> I have this issue today (new install right now) and no log file in the wemod launcher folder only the following (I just noticed the log should be in home/deck its also not there): bin file .git wemod.bat wemod ( no ext but shows as python - does this need to be .log) util.py setup.py requirements.txt readme.md LICENSE changelog.md .gitignore

To get a report in this case:
1. make sure steam is closed
2. start a terminal
3. run steam in the terminal (just type "steam" and hit enter)
4. the terminal will now display any errors
5. report back here

**Comment by robangus** [comment] 2024-05-19 10:38
> > > I think i found the problem, i fixed it here [commit fix string](https://github.com/DaniAsh551/wemod-launcher/commit/1801e03175535252180266eb6f4867b87a66658d), So to fix the problem delete the wemod-laucher folder and run [step 3](https://github.com/DaniAsh551/wemod-launcher?tab=readme-ov-file#step-3-installing-wemod-launcher) once more
> > 
> > 
> > I have this issue today (new install right now) and no log file in the wemod launcher folder only the following (I just noticed the log should be in home/deck its also not there): bin file .git wemod.bat wemod ( no ext but shows as python - does this need to be .log) util.py setup.py requirements.txt readme.md LICENSE changelog.md .gitignore
> 
> To get a report in this case:
> 
> 1. make sure steam is closed
> 2. start a terminal
> 3. run steam in the terminal (just type "steam" and hit enter)
> 4. the terminal will now display any errors
> 5. report back here

(1)(deck@steamdeck ~)$ steam
steam.sh[6635]: Running Steam on steamos rolling 64-bit
steam.sh[6635]: STEAM_RUNTIME is enabled automatically
setup.sh[6716]: Steam runtime environment up-to-date!
steam.sh[6635]: Steam client's requirements are satisfied
[2024-05-19 11:37:56] Startup - updater built May 16 2024 20:10:34
[2024-05-19 11:37:56] Startup - Steam Client launched with: '/home/deck/.local/share/Steam/ubuntu12_32/steam' '-steamdeck'
[2024-05-19 11:37:56] Opted in to client beta 'steamdeck_stable' via beta file
You are in the 'steamdeck_stable' client beta.
05/19 11:37:56 minidumps folder is set to /tmp/dumps
05/19 11:37:56 Init: Installing breakpad exception handler for appid(steam)/version(1715891371)/tid(6766)
[2024-05-19 11:37:56] Loading cached metrics from disk (/home/deck/.local/share/Steam/package/steam_client_metrics.bin)
[2024-05-19 11:37:56] Using the following download hosts for Public, Realm steamglobal
[2024-05-19 11:37:56] 1. https://client-update.akamai.steamstatic.com, /, Realm 'steamglobal', weight was 1000, source = 'update_hosts_cached.vdf'
[2024-05-19 11:37:56] 2. https://cdn.cloudflare.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'update_hosts_cached.vdf'
[2024-05-19 11:37:56] 3. https://cdn.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
[2024-05-19 11:37:56] Verifying installation...
[2024-05-19 11:37:56] Verification complete
UpdateUI: skip show logo
Steam logging initialized: directory: /home/deck/.local/share/Steam/logs

XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xe8f3c370
XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xe8f3acc0
/usr/share/themes/Breeze/gtk-2.0/widgets/entry:70: error: unexpected identifier 'direction', expected character '}'
/usr/share/themes/Breeze/gtk-2.0/widgets/styles:36: error: invalid string constant "combobox_entry", expected valid string constant
steamwebhelper.sh[6792]: === Sun May 19 11:37:57 AM IST 2024 ===
steamwebhelper.sh[6792]: Starting steamwebhelper under bootstrap sniper steam runtime at /home/deck/.local/share/Steam/ubuntu12_64/steam-runtime-sniper
Steam Runtime Launch Service: starting steam-runtime-launcher-service
Steam Runtime Launch Service: steam-runtime-launcher-service is running pid 6917
CAppInfoCacheReadFromDiskThread took 96 milliseconds to initialize
bus_name=com.steampowered.PressureVessel.LaunchAlongsideSteam
BRefreshApplicationsInLibrary 1: 1ms
BuildCompleteAppOverviewChange: 370 apps
RegisterForAppOverview 1: 39ms
RegisterForAppOverview 2: 40ms
^C^CSteam Runtime Launch Service: steam-runtime-launcher-service pid 6917 exited
Steam Runtime Launch Service: starting steam-runtime-launcher-service
Steam Runtime Launch Service: steam-runtime-launcher-service is running pid 7648
bus_name=com.steampowered.PressureVessel.LaunchAlongsideSteam
****

**Comment by marvin1099** [comment] 2024-05-19 10:41
@robangus
Please provide the output after you clicked on play in steam

**Comment by robangus** [comment] 2024-05-19 10:42
> @robangus Please provide the output after you clicked on play in steam

Sorry added as an edit to the above but: steam.sh[6635]: Running Steam on steamos rolling 64-bit
steam.sh[6635]: STEAM_RUNTIME is enabled automatically
setup.sh[6716]: Steam runtime environment up-to-date!
steam.sh[6635]: Steam client's requirements are satisfied
[2024-05-19 11:37:56] Startup - updater built May 16 2024 20:10:34
[2024-05-19 11:37:56] Startup - Steam Client launched with: '/home/deck/.local/share/Steam/ubuntu12_32/steam' '-steamdeck'
[2024-05-19 11:37:56] Opted in to client beta 'steamdeck_stable' via beta file
You are in the 'steamdeck_stable' client beta.
05/19 11:37:56 minidumps folder is set to /tmp/dumps
05/19 11:37:56 Init: Installing breakpad exception handler for appid(steam)/version(1715891371)/tid(6766)
[2024-05-19 11:37:56] Loading cached metrics from disk (/home/deck/.local/share/Steam/package/steam_client_metrics.bin)
[2024-05-19 11:37:56] Using the following download hosts for Public, Realm steamglobal
[2024-05-19 11:37:56] 1. https://client-update.akamai.steamstatic.com, /, Realm 'steamglobal', weight was 1000, source = 'update_hosts_cached.vdf'
[2024-05-19 11:37:56] 2. https://cdn.cloudflare.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'update_hosts_cached.vdf'
[2024-05-19 11:37:56] 3. https://cdn.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
[2024-05-19 11:37:56] Verifying installation...
[2024-05-19 11:37:56] Verification complete
UpdateUI: skip show logo
Steam logging initialized: directory: /home/deck/.local/share/Steam/logs

XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xe8f3c370
XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xe8f3acc0
/usr/share/themes/Breeze/gtk-2.0/widgets/entry:70: error: unexpected identifier 'direction', expected character '}'
/usr/share/themes/Breeze/gtk-2.0/widgets/styles:36: error: invalid string constant "combobox_entry", expected valid string constant
steamwebhelper.sh[6792]: === Sun May 19 11:37:57 AM IST 2024 ===
steamwebhelper.sh[6792]: Starting steamwebhelper under bootstrap sniper steam runtime at /home/deck/.local/share/Steam/ubuntu12_64/steam-runtime-sniper
Steam Runtime Launch Service: starting steam-runtime-launcher-service
Steam Runtime Launch Service: steam-runtime-launcher-service is running pid 6917
CAppInfoCacheReadFromDiskThread took 96 milliseconds to initialize
bus_name=com.steampowered.PressureVessel.LaunchAlongsideSteam
BRefreshApplicationsInLibrary 1: 1ms
BuildCompleteAppOverviewChange: 370 apps
RegisterForAppOverview 1: 39ms
RegisterForAppOverview 2: 40ms
^C^CSteam Runtime Launch Service: steam-runtime-launcher-service pid 6917 exited
Steam Runtime Launch Service: starting steam-runtime-launcher-service
Steam Runtime Launch Service: steam-runtime-launcher-service is running pid 7648
bus_name=com.steampowered.PressureVessel.LaunchAlongsideSteam
WARNING: discarding _NET_WM_PID 2 as invalid for X11 window - use specialized XCB_X11_TO_PID function!
WARNING: discarding _NET_WM_PID 2 as invalid for X11 window - use specialized XCB_X11_TO_PID function!
WARNING: discarding _NET_WM_PID 2 as invalid for X11 window - use specialized XCB_X11_TO_PID function!
WARNING: discarding _NET_WM_PID 2 as invalid for X11 window - use specialized XCB_X11_TO_PID function!
WARNING: discarding _NET_WM_PID 2 as invalid for X11 window - use specialized XCB_X11_TO_PID function!
WARNING: discarding _NET_WM_PID 2 as invalid for X11 window - use specialized XCB_X11_TO_PID function!
WARNING: discarding _NET_WM_PID 2 as invalid for X11 window - use specialized XCB_X11_TO_PID function!
WARNING: discarding _NET_WM_PID 2 as invalid for X11 window - use specialized XCB_X11_TO_PID function!
wine: using kernel write watches, use_kernel_writewatch 2.
fsync: up and running.
wine: using kernel write watches, use_kernel_writewatch 2.
wine: using kernel write watches, use_kernel_writewatch 2.
wine: using kernel write watches, use_kernel_writewatch 2.
wine: using kernel write watches, use_kernel_writewatch 2.
wine: using kernel write watches, use_kernel_writewatch 2.
wine: using kernel write watches, use_kernel_writewatch 2.
wine: using kernel write watches, use_kernel_writewatch 2.
wine: using kernel write watches, use_kernel_writewatch 2.
wine: using kernel write watches, use_kernel_writewatch 2.
wine: using kernel write watches, use_kernel_writewatch 2.
/bin/sh\0-c\0WEMOD_LOG=/home/deck/wemod-launcher/wemod.log /home/deck/wemod-launcher/wemod /home/deck/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=1086940 -- /home/deck/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/home/deck/.local/share/Steam/steamapps/common/SteamLinuxRuntime_sniper'/_v2-entry-point --verb=waitforexitandrun -- '/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton9-5'/proton waitforexitandrun  '/home/deck/.local/share/Steam/steamapps/common/Baldurs Gate 3/Launcher/LariLauncher.exe'\0
chdir "/home/deck/.local/share/Steam/steamapps/common/Baldurs Gate 3/bin"
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Traceback (most recent call last):
  File "/home/deck/wemod-launcher/wemod", line 3, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
WARNING: discarding _NET_WM_PID 2 as invalid for X11 window - use specialized XCB_X11_TO_PID function!
Uploaded AppInterfaceStats to Steam
WARNING: discarding _NET_WM_PID 2 as invalid for X11 window - use specialized XCB_X11_TO_PID function!
WARNING: discarding _NET_WM_PID 2 as invalid for X11 window - use specialized XCB_X11_TO_PID function!
WARNING: discarding _NET_WM_PID 2 as invalid for X11 window - use specialized XCB_X11_TO_PID function!
[2024-05-19 11:39:57] Background update loop checking for update. . .
[2024-05-19 11:39:57] Checking for available updates...
[2024-05-19 11:39:57] Downloading manifest: https://client-update.akamai.steamstatic.com/steam_client_steamdeck_stable_ubuntu12?t=2200074155
[2024-05-19 11:39:57] Manifest download: send request
[2024-05-19 11:39:58] Manifest download: waiting for download to finish
[2024-05-19 11:39:58] Manifest download: finished
[2024-05-19 11:39:58] Download skipped: /steam_client_steamdeck_stable_ubuntu12?t=2200074155 version 1715891371, installed version 1715891371, existing pending version 0
[2024-05-19 11:39:58] Nothing to do

**Comment by marvin1099** [comment] 2024-05-19 10:45
Got it i think, there seams to be some problem with a python module, if you can install it, i will try and fix this.
Traceback (most recent call last):
File "/home/deck/wemod-launcher/wemod", line 3, in
import requests
ModuleNotFoundError: No module named 'requests'

**Comment by marvin1099** [comment] 2024-05-19 10:54
I found a easy fix, now it works, even when the requests module is missing, it will download it then.

**Comment by DaniAsh551** [comment] 2024-05-19 10:57
> I found a easy fix, now it works, even when the requests module is missing, it will download it then.

yeah, if the `requirements.txt` includes the module, it should be installed automatically
but it might only work in the next launch

**Comment by marvin1099** [comment] 2024-05-19 11:01
@wfmota i assume your issue is fixed too, so i will close this issue 
@robangus i know yours is fixed.

> yeah, if the requirements.txt includes the module, it should be installed automatically
but it might only work in the next launch

As mentioned it works now, there was a something missing in the download prefix update, if you get the newest version, the problem is gone.

**Comment by DaniAsh551** [comment] 2024-05-19 11:02
also regarding commit 1801e03 and other like it, maybe we should implement a basic CI/CD to do some sanity checks? I have a few ideas about this, but maybe the discussions page will be more suitable to discuss this.

**Closed by marvin1099** 2024-05-19 11:01 UTC

**Comment by robangus** [comment] 2024-05-19 11:09
> @wfmota i assume your issue is fixed too, so i will close this issue @robangus i know yours is fixed.
> 
> > yeah, if the requirements.txt includes the module, it should be installed automatically
> > but it might only work in the next launch
> 
> As mentioned it works now, there was a something missing in the download prefix update, if you get the newest version, the problem is gone.

I now have a log file. Issue is persisting but seems to have progressed slightly.

FreeSimpleGUI is missing
requests is missing
Dependencies missing, creating virtual environment...
Virtual environment created successfully.
pip not found. Downloading...
pip finished
pip finished
Re-running script within virtual environment
All dependencies are already installed.
Looking for init file '/home/deck/.local/share/Steam/steamapps/compatdata/1086940/pfx/.wemod_installer'
Loking for compatible wine prefixes in '/home/deck/.local/share/Steam/steamapps/compatdata' with proton version '9.5'
ERR:
'NoneType' object is not subscriptable


ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
FreeSimpleGUI is missing
requests is missing
Dependencies missing, creating virtual environment...
Virtual environment created successfully.
pip not installed. Using local pip.pyz
pip finished
pip finished
Re-running script within virtual environment
All dependencies are already installed.
Looking for init file '/home/deck/.local/share/Steam/steamapps/compatdata/1086940/pfx/.wemod_installer'
Loking for compatible wine prefixes in '/home/deck/.local/share/Steam/steamapps/compatdata' with proton version '9.5'
ERR:
'NoneType' object is not subscriptable


ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
FreeSimpleGUI is missing
requests is missing
Dependencies missing, creating virtual environment...
Virtual environment created successfully.
pip not installed. Using local pip.pyz
pip finished
pip finished
Re-running script within virtual environment
All dependencies are already installed.
Looking for init file '/home/deck/.local/share/Steam/steamapps/compatdata/1086940/pfx/.wemod_installer'
Loking for compatible wine prefixes in '/home/deck/.local/share/Steam/steamapps/compatdata' with proton version '8.32'
ERR:
'NoneType' object is not subscriptable


ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
FreeSimpleGUI is missing
requests is missing
Dependencies missing, creating virtual environment...
Virtual environment created successfully.
pip not installed. Using local pip.pyz
pip finished
pip finished
Re-running script within virtual environment
All dependencies are already installed.
Looking for init file '/home/deck/.local/share/Steam/steamapps/compatdata/1086940/pfx/.wemod_installer'
Loking for compatible wine prefixes in '/home/deck/.local/share/Steam/steamapps/compatdata' with proton version '8.32'
ERR:
'NoneType' object is not subscriptable


ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.

**Comment by DaniAsh551** [comment] 2024-05-19 11:20
`'NoneType' object is not subscriptable` is pretty vague, maybe we need to better the logging functionality.

@robangus  you can set a log file location for wemod with `WEMOD_LOG=/home/deck/wemod.log` or something similar, so that you dont need to run steam from terminal - this will also give the wemod related logs and not steam logs

**Comment by robangus** [comment] 2024-05-19 11:25
> `'NoneType' object is not subscriptable` is pretty vague, maybe we need to better the logging functionality. maybe marvin has some idea.
> 
> @robangus you can set a log file location for wemod with `WEMOD_LOG=/home/deck/wemod.log` or something similar, so that you dont need to run steam from terminal - this will also give the wemod related logs and not steam logs

Sorry for the confusion that is from the log file which is now correctly generating.

**Comment by DaniAsh551** [comment] 2024-05-19 11:51
@marvin1099 already opened a new discussion thread here: https://github.com/DaniAsh551/wemod-launcher/discussions/45
