### ISSUE TITLE
won't launch

### ISSUE THREAD

**Issue by Diamondnite27** [DaniAsh551/wemod-launcher#83] opened 2024-06-20 20:28 UTC
i can install proton and wemod but when i put the launch options in and go back to open the game it says launching but the doesn't launch.
can anyone help i have we mod installed on pc ok but it won't work on my steam deck

**Comment by marvin1099** [comment] 2024-06-20 20:36
I'm going to need the wemod.log file if it exists.
If not close steam, open a console, type `steam`, hit enter, start the wemod-launcher game and copy the output to this issue.

**Comment by marvin1099** [comment] 2024-06-20 20:51
@Diamondnite27 if the logfile exists then it will be in the folder `/home/$USER/wemod-launcher`
$USER will need to ve replaced by your username.
On SteamOS the username is `deck`

**Comment by Diamondnite27** [comment] 2024-06-20 21:03
> @Diamondnite27 if the logfile exists then it will be in the folder `/home/$USER/wemod-launcher` $USER will need to ve replaced by your username. On SteamOS the username is `deck`

i can't find the logfile in the wemod launcher folder

**Comment by marvin1099** [comment] 2024-06-20 21:32
As mentiined if the file is nit there close steam, open a console, type steam, hit enter, start the wemod-launcher game and copy the steam console output to this issue.

**Comment by Diamondnite27** [comment] 2024-06-20 21:38
> As mentioned if the file is nit there close steam, open a console, type steam, hit enter, start the wemod-launcher game and copy the steam console output to this issue.

i can't start the wemod-launcher game or find the steam console output

**Comment by Diamondnite27** [comment] 2024-06-20 21:47
![image](https://github.com/DaniAsh551/wemod-launcher/assets/173407222/32cf32bd-1f73-4e28-928f-3e9be59a437a)

**Comment by Diamondnite27** [comment] 2024-06-20 21:52
> As mentioned in the error, proton seems to not be active, you will have to go to compatabilty and force proton / pe-proton

i have done that still nothing

**Comment by marvin1099** [comment] 2024-06-20 21:57
did you use ge-proton?
try to update to the newest version as well for that run:

    cd home/$USER/wemod-launcher
    git reset --hard origin
    git pull
    sudo chmod -R ug+x .

**Comment by Diamondnite27** [comment] 2024-06-20 21:58
![image](https://github.com/DaniAsh551/wemod-launcher/assets/173407222/03d85ed7-8665-44cb-aa21-5f5be830ae4b)

**Comment by Diamondnite27** [comment] 2024-06-20 21:58
![image](https://github.com/DaniAsh551/wemod-launcher/assets/173407222/05fa1784-d7dc-4b20-9b01-ccde1a79db97)

**Comment by Diamondnite27** [comment] 2024-06-20 22:01
> did you use ge-proton?
> 
> Also try to update to the newest version as well for that run:
> 
> 
> 
>     cd home/$USER/wemod-launcher
> 
>     git reset --hard origin
> 
>     git pull
> 
>     sudo chmod -R ug+x .

I will see if i can do this do i put that in console i did the git clone from the guide but didn't do the sudo i am new to all this sorry to be a pain

**Comment by marvin1099** [comment] 2024-06-20 22:02
yust see if that works if not will have to look for other solutions

**Comment by Diamondnite27** [comment] 2024-06-20 22:07
![image](https://github.com/DaniAsh551/wemod-launcher/assets/173407222/2a8627eb-4a7b-40af-b6aa-c1b67dbeddd8)

**Comment by marvin1099** [comment] 2024-06-20 22:09
you are missing a / at the start just copy and paste this it sold work without any changes:

    cd home/$USER/wemod-launcher
    git reset --hard origin
    git pull
    sudo chmod -R ug+x .

**Comment by Diamondnite27** [comment] 2024-06-20 22:14
![image](https://github.com/DaniAsh551/wemod-launcher/assets/173407222/59e01933-d936-42ff-a75b-e6876925084b)

**Comment by marvin1099** [comment] 2024-06-20 22:16
sadly will have to fix this tomorrow, i will have to go to sleep now, i don't like to be tired after waking up from my alarm.
you can try to delete proton ge and re-download as well as following the [full guide](https://github.com/DaniAsh551/wemod-launcher/wiki/Full-guide).
also the . is missing on the last command its `sudo chmod -R ug+x .` not `sudo chmod -R ug+x` there should be a dot at the end.
I will come back and help tomorrow, but for now i will leave.

**Comment by Diamondnite27** [comment] 2024-06-20 22:18
thank you for trying to help

**Comment by marvin1099** [comment] 2024-06-21 06:02
@Diamondnite27 So im back, did you get anything more done?
You can also try proton instead of ge-proton if the reinstall of ge-proton did not work.

**Comment by marvin1099** [comment] 2024-06-21 07:03
@Diamondnite27 I recently pushed a update, please run:
```
cd /home/$USER/wemod-launcher
git reset --hard origin
git pull
sudo chmod -R ug+x .
```
<br>

And as mentioned:
- Delete GE-Proton and Re-download GE-Proton if you have not done this yet,  
- Also try the normal proton if GE-Proton still gives the same error and see it that works,
- Report any new errors back so i can help you out.
- If everything works please close the issue so i know that the problem is solved.

**Comment by Diamondnite27** [comment] 2024-06-21 07:21
Hi im just at work at the moment so wont be able to check until later i believe it did work as the wemod login screen loaded but then my deck stopped responding and wouldn't let me type in my login details. I am going to try again tonight.

**Comment by marvin1099** [comment] 2024-06-21 09:05
> Hi im just at work at the moment so wont be able to check until later i believe it did work as the wemod login screen loaded but then my deck stopped responding and wouldn't let me type in my login details. I am going to try again tonight.

If you got past the error from the last image you are basicly done, that login screen sounds like you have done it.

**Comment by Diamondnite27** [comment] 2024-06-21 14:39
![image](https://github.com/DaniAsh551/wemod-launcher/assets/173407222/273918ff-943a-4547-bb9c-893be9d27e15)

Its loaded but can't sign in

**Comment by marvin1099** [comment] 2024-06-21 15:05
Use desktop mode to login then, after you are logged in you won't have to do it anymore, also a keyboard / mouse may help, if you don't have these you can use Rustdesk to connect to your steam deck from for phone or a other computer

**Comment by Diamondnite27** [comment] 2024-06-21 17:22
> Use desktop mode to login then, after you are logged in you won't have to do it anymore, also a keyboard / mouse may help, if you don't have these you can use Rustdesk (in desktop mode) to connect to your steam deck from for phone or a other computer  

Thank you i will close this now as it is running

**Closed** 2024-06-21 17:22 UTC
